### PR TITLE
Displays expenditures opposing candidate if we have any reported

### LINKED ISSUE #231: Add expenditures opposing candidates
The backend is now providing opposing_money for candidates and a list of opposing money for committees.
The front end should display this.

### PR DESCRIPTION
**Pull request by KyleW**
Resolves #231 

Looks like this:
screen shot 2016-10-31 at 9 16 25 am

### CODE REVIEW

**Comment by mikeubell** [comment]
Does it link to the list of expenditures?

**Comment by KyleW** [comment]
It does not. But that would be cool and pretty easy if the data is there.
Is that returned in the call for candidate/:id/opposing?

**Comment by mikeubell** [comment]
That looks right.  It just like the supporting side.

**Comment by KyleW** [comment]
@mikeubell Merging this as is since I'd rather show a topline number than nothing, but will poke @tdooner about where I can find the individual contributions and post a follow up as quick as I can.

**Pull request merged**
