### PR TITLE
Hit backend api

### PR DESCRIPTION
**Pull request by adborden**
@bcipolli Great work! I took your branch and made some additions to get travis working. Has nothing to do with your branch, really. Travis is pulling in the latest dependencies and getting tripped up. For example, it was pulling in angular 1.5 and the app wasn't even building correclty.

To make sure things are good going forward, the only addition I would make to your test pass would be to spin up the app and make sure it's running in addition to making sure the tests pass.

The UI-router has basically 0 test coverage. This is sort of expected, since the state config is mostly just a configuration, but unfortunately the simple `resolve` statements can have bugs in them. Running `gulp build` and spot checking some of the state transitions should be sufficient.

### CODE REVIEW

**Comment by bcipolli** [comment]
@adborden Awesome! Thanks for doing that, will take a look at the code and try to learn! Should have feedback shortly.

**Comment by bcipolli** [comment]
>To make sure things are good going forward, the only addition I would make to your test pass would be to spin up the app and make sure it's running in addition to making sure the tests pass.

Not sure exactly what this means. "Spin up the app" === `gulp build`?  "Make sure it's running" == ?

>The UI-router has basically 0 test coverage. This is sort of expected, since the state config is mostly just a configuration, but unfortunately the simple resolve statements can have bugs in them. Running gulp build and spot checking some of the state transitions should be sufficient.

Not sure how to "spot check some of the state transitions". Do you mean manual testing via the web UI?

newbie alert...

**Comment by adborden** [comment]
>Not sure exactly what this means. "Spin up the app" === `gulp build`?  "Make sure it's running" == ?

Yep, `gulp build` and make sure the page loads.

> Not sure how to "spot check some of the state transitions". Do you mean manual testing via the web UI?

Yeah, ad hoc testing. Pro tip: you can use the demo links in the nav and just make sure things aren't egregiously broken.

> ~~newbie alert...~~

**Comment by bcipolli** [comment]
Cool, thanks @adborden . How do you feel about automated Selenium tests to do this for us?

**Comment by bcipolli** [comment]
OK, I've tested this manually. Will look at creating automated tests (see #96). Let's merge this!

**Comment by adborden** [comment]
On Thu, 2016-02-11 at 00:12 -0800, Ben Cipollini <notifications@github.com> wrote:
> Cool, thanks @adborden . How do you feel about automated Selenium tests to do this for us?

I was trying to avoid it, hoping that the fronted would be dead simple.
Selenium/protractor are kind of overkill for the app because there's
very little UI interactions. Only search and links.

But I get your point. It's really easy to typo something and suddenly
the whole application won't load. After writing unit tests in karma for
out frontend components, it's clear that trying to get the whole app to
load in karma is going to become a pain in the butt, so using a full
blown browser via Selenium starts to make sense.

**Pull request merged**
