### PR TITLE
[WIP] Feature/odca markdown

### LINKED ISSUE #8: Content for FAQ page
A good start: http://www.opendisclosure.io/faq#

### LINKED ISSUE #21: Write short definitions for "non-itemized contributions" and "independent expenditure committees"
Everyone write a super short definition that we can use in the hover environment.

### PR DESCRIPTION
**Pull request by adborden**
This is using some draft content for the FAQ and About page, but is ready to be reviewed from a technical perspective.

Resolves https://github.com/caciviclab/disclosure-frontend/issues/167, resolves https://github.com/caciviclab/disclosure-frontend/issues/166, resolves https://github.com/caciviclab/disclosure-frontend/issues/101, resolves https://github.com/caciviclab/disclosure-frontend/issues/9, resolves #21, resolves #8 

@sfdoran How are you with HTML? I decided to include the pages as [markdown](https://help.github.com/articles/basic-writing-and-formatting-syntax/) so that you don't need to be an expert to edit the content. This is the same markdown flavor that github uses for formatting comments and wikis. [The content looks like this](https://raw.githubusercontent.com/caciviclab/disclosure-frontend/e23ae0c87161fc1e7c135926a5263f1c7f9b1560/app/components/appMainModule/faqPageModule/faqPage.md) in it's raw form. You can even [edit it right on github](https://github.com/caciviclab/disclosure-frontend/edit/feature/odca-markdown/app/components/appMainModule/faqPageModule/faqPage.md).

cc @KyleW @elinaru

### CODE REVIEW

**Comment by adborden** [comment]
#152 is not actually fixed by this, that story is about the styling which is not included.

**Comment by adborden** [comment]
Fixes #21

**Comment by adborden** [comment]
Fixes #8

**Comment by adborden** [comment]
@KyleW I'm merging these in time for @sfdoran's bug bash, but I can follow up on any comments you have.

**Comment by KyleW** [comment]
Looks fine.

**Pull request merged**
