### PR TITLE
Read settings from environment

### PR DESCRIPTION
**Pull request by adborden**
@bcipolli this should allow you to run the frontend tests against your local backend. Does this work for you?

    $ DISCLOSURE_SWAGGER_SPEC='http://localhost:8000/docs/api-docs/' gulp test

I tested this against your open PR https://github.com/caciviclab/disclosure-backend/pull/151

### CODE REVIEW

**Comment by adborden** [comment]
Tests are failing because the current live backend is having some issues.

**Comment by bcipolli** [comment]
With this change, does it make sense to install a local backend when doing
tests? Deployment server will frequently be behind..

**Comment by bcipolli** [comment]
P.s. thank you! I will try this in the morning, but this should really
help!!

**Comment by adborden** [comment]
I don't think that makes sense here. BTW @jnmarcus have you tried setting up the django app? If folks don't even have python tools installed, I'm not sure we'll be able to run tests against a local backend anyway. Might make more sense to spin up a frontend app for the backend tests.

BUT I'm not crazy about the idea of spinning up one project within the other for testing. If we're really interested in doing that, I think our time would be better spent by serving the fronted via django. It resolves this in addition to other issues.

What's the problem you're trying to solve? I agree that the backend/frontend development process has too much friction. Hopefully this change will relieve some of it.

We gate the frontend deploys with a branch (master). So we can actually deploy the frontend manually when we update the backend. It's not a problem if the live backend is out of date, except if you want to develop against the latest backend changes. However, it looks to me like the folks who are interested in that will set up a local backend and the folks who aren't are okay to wait for it to be live.

**Comment by bcipolli** [comment]
>What's the problem you're trying to solve?

Making front-end PRs that change frontend/backend interactions, without having to publish backend code to the release site. Right now there's no incremental way to push frontend & backend forward; backend goes forward and breaks frontend, frontend cannot be tested via travis to see if it works unless the backend code gets published... which means we have to be release-ready.

It takes very little time to set this up in the frontend travis tests. Just do a `git clone` of the backend, and copy over some lines from the backend travis file. Seems super-simple to me, less than an hour's worth of work.

Otherwise, I find little friction in frontend/backend development. It's just the ability to run CI tests is not there.

**Comment by bcipolli** [comment]
This works great for me in local testing. Let's merge it and continue test discussion as needed, elsewhere.

**Pull request merged**
