### PR TITLE
Add backend repo information

### PR DESCRIPTION
**Pull request by bcipolli**
Add a `requirements.txt` file, with instructions on how to install the proper test backend.

### CODE REVIEW

**Comment by adborden** [comment]
This isn't the approach we should take for talking to the backend.. If frontend folks want talk to a local `disclosure-backend`, they should read the [disclosure-backend README](https://github.com/caciviclab/disclosure-backend/blob/master/README.md) to set it up.

Instead, we should make it configurable/easier to set [which backend](https://github.com/caciviclab/disclosure-frontend-alpha/blob/master/app/components/services/disclosure/service.js#L6) you want to talk to via a build setting.

**Comment by bcipolli** [comment]
>This isn't the approach we should take for talking to the backend.. If frontend folks want talk to a local disclosure-backend, they should read the disclosure-backend README to set it up.

I agree for later in the project, but right now the builds change quickly and get out of sync easily. Keeping an explicit marker of how each branch relates to a back-end build is helpful--just as you asked about version information.

This is going to be particularly true as I imagine each API endpoint will be addressed in separate pull requests that require explicit ties between frontend and backend. To me, the easiest way to coordinate (and avoid mismatched versions in all the async permutations that can happen with branches on github), I think this is the right thing for the project right now.

I say that specifically because this has been difficult for me to manage, alone, let alone across a number of contributors.

**Comment by bcipolli** [comment]
I've pared this down to adding the `requirements.txt` file and rebased on the latest code.

**Comment by bcipolli** [comment]
Since there's so little activity in this repo, I'm fine to close this for now. We can revisit as needed.

**Pull request closed without merging**
