### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by adborden**
Update the homepage as per mocks. Here are the notes from the UI hitlist

- [x] Sacramento hero. Copyright is cut off on the bottom.
- [x] Text is different, use text from mocks.
- [x] Black overlay at 40% opacity on sacramento hero.
- [x] Home page content coming from Elina.
- [x] Need a min-height to prevent search bar from getting cutoff by footer

**1200px wide**
screenshot from 2016-09-22 22-04-40

**320px wide**
screenshot from 2016-09-22 22-07-01

cc @KyleW @elinaru

### CODE REVIEW

**Comment by adborden** [comment]
Fixes #151

**Comment by adborden** [comment]
Fixes #150

**Comment by adborden** [comment]
Fixes #69

**Comment by KyleW** [comment]
Looks good. Merging.

**Pull request merged**
